### ISSUE TITLE
_PMX Chunks behave poorly and will throw out of range

### ISSUE THREAD

**Issue by nobuyukinyuu** [XCVG/WaveLoader#2]
The issue is related to https://github.com/mono/taglib-sharp/issues/76, with a proposed fix in https://github.com/mono/taglib-sharp/issues/101.  Basically, this chunk will lie about its size and not include a NUL character in its count.  I'm assuming as part of the spec, all chunks are aligned to word size, so thus the iterator should probably snap to the next word boundary if it determines the chunk size.  I haven't yet run into any other tags which have caused the file read to misalign, but if I do, I'll report the issue.

Attached is an example waveform with a _PMX chunk that will cause the current `Load` routine to crash.
[poit.zip](https://github.com/XCVG/WaveLoader/files/8936733/poit.zip)

**Comment by XCVG** [comment]
Tentative fix is in, still needs testing. My suite of baseline test files is in an archive somewhere and I need to dust that off. Once it's verified fixed and still working with everything else I'll draw up another release.

**Comment by XCVG** [comment]
Fixed in v1.1.2
